import "./globals.css";
import Nav1 from "@/components/nav1";

export const metadata = {
  title: "Restaurant Reservation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav1/>
        {children}
      </body>
    </html>
  );
}
